#spring.application.name=fullstack-tech-forb
spring:
  profile.active: dev, test, prod
  datasource:
    #url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    url: jdbc:mysql://localhost/forbtech
    #username: ${DB_USER}
    username: root
    #password: ${DB_PASSWORD}
    password: ${DB_PSWCAC}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: railway
    validate-on-migrate: false
